#!/usr/bin/env bash

# Usage:
#  bldbeta [release]

# Requires a cook script on $PATH.

DEFAULT_RELEASE=2.6.3.B1
RELEASE=${1:-$DEFAULT_RELEASE}
DEST=$PWD
RECIPE=$PWD/recipes/index.$RELEASE.html.recipe
cook $RECIPE index.$RELEASE.html -q
RECIPE=$PWD/recipes/empty.$RELEASE.html.recipe
cook $RECIPE empty.$RELEASE.html -q
cook  $RECIPE -d$DEST -q -o compressed.$RELEASE.html -cr -Cr -Dr
cook  $RECIPE -d$DEST -q -j -o twcore.$RELEASE.js
